import Navigations from "@/starter/components/Navigation";
import Logo from "./components/Logo";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Logo />
      <Navigations />
      <body>{children}</body>
    </html>
  );
}
